// 定义该页面的视频数据
const videoData = [
    { srcWebm: "./video/mmd/mmd_mache.webm", srcMp4: "./video/mmd/mmd_mache.mp4", label: "交互动效展示" },
    { srcWebm: "./video/mmd/mmd_clickhouse.webm", srcMp4: "./video/mmd/mmd_clickhouse.mp4", label: "交互动效展示" },
    { srcWebm: "./video/mmd/mmd_fx_lvup02.webm", srcMp4: "./video/mmd/mmd_fx_lvup02.mp4", label: "交互动效展示" },
    { srcWebm: "./video/mmd/mmd_clicktree.webm", srcMp4: "./video/mmd/mmd_clicktree.mp4", label: "交互动效展示" },
    { srcWebm: "./video/mmd/mmd_fish_girl.webm", srcMp4: "./video/mmd/mmd_fish_girl.mp4", label: "钓鱼女孩动画展示" },
    { srcWebm: "./video/king.webm", srcMp4: "./video/king.mp4", label: "战斗角色动作展示" },
    { srcWebm: "./video/mmd/mmd_fx_card01.webm", srcMp4: "./video/mmd/mmd_fx_card01.mp4", label: "抽卡金鱼动画展示" },
    { srcWebm: "./video/mmd/mmd_fx01.webm", srcMp4: "./video/mmd/mmd_fx01.mp4", label: "飘花动画展示" },
    { srcWebm: "./video/mmd/mmd_fx02.webm", srcMp4: "./video/mmd/mmd_fx02.mp4", label: "飘花动画展示" },
    { srcWebm: "./video/mmd/mmd_fx03.webm", srcMp4: "./video/mmd/mmd_fx03.mp4", label: "飘花动画展示" },
    { srcWebm: "./video/mmd/mmd_fx04.webm", srcMp4: "./video/mmd/mmd_fx04.mp4", label: "飘花动画展示" },
    { srcWebm: "./video/mmd/mmd_fx05.webm", srcMp4: "./video/mmd/mmd_fx05.mp4", label: "飘花动画展示" },
    { srcWebm: "./video/mmd/mmd_login.webm", srcMp4: "./video/mmd/mmd_login.mp4", label: "游戏登陆动画展示" },
    { srcWebm: "./video/mmd/mmd_role02.webm", srcMp4: "./video/mmd/mmd_role02.mp4", label: "立绘角色待机呼吸动画展示" },
    { srcWebm: "./video/mmd/mmd_role03.webm", srcMp4: "./video/mmd/mmd_role03.mp4", label: "立绘角色待机呼吸动画展示" },
    { srcWebm: "./video/mmd/mmd_role04.webm", srcMp4: "./video/mmd/mmd_role04.mp4", label: "立绘角色待机呼吸动画展示" },
    { srcWebm: "./video/mmd/mmd_role05.webm", srcMp4: "./video/mmd/mmd_role05.mp4", label: "立绘角色待机呼吸动画展示" },
    { srcWebm: "./video/mmd/mmd_role06.webm", srcMp4: "./video/mmd/mmd_role06.mp4", label: "立绘角色待机呼吸动画展示" },
    { srcWebm: "./video/mmd/mmd_role07.webm", srcMp4: "./video/mmd/mmd_role07.mp4", label: "立绘角色待机呼吸动画展示" },
    { srcWebm: "./video/mmd/mmd_role08.webm", srcMp4: "./video/mmd/mmd_role08.mp4", label: "立绘角色待机呼吸动画展示" },
    // 萌萌哒Q角色
    { srcWebm: "./video/mmd/mmd_q_01.webm", srcMp4: "./video/mmd/mmd_q_01.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_02.webm", srcMp4: "./video/mmd/mmd_q_02.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_03.webm", srcMp4: "./video/mmd/mmd_q_03.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_04.webm", srcMp4: "./video/mmd/mmd_q_04.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_05.webm", srcMp4: "./video/mmd/mmd_q_05.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_06.webm", srcMp4: "./video/mmd/mmd_q_06.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_07.webm", srcMp4: "./video/mmd/mmd_q_07.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_08.webm", srcMp4: "./video/mmd/mmd_q_08.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_09.webm", srcMp4: "./video/mmd/mmd_q_09.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_10.webm", srcMp4: "./video/mmd/mmd_q_10.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_11.webm", srcMp4: "./video/mmd/mmd_q_11.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_12.webm", srcMp4: "./video/mmd/mmd_q_12.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_13.webm", srcMp4: "./video/mmd/mmd_q_13.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_14.webm", srcMp4: "./video/mmd/mmd_q_14.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_15.webm", srcMp4: "./video/mmd/mmd_q_15.mp4", label: "Q角色休闲动作展示" },
    { srcWebm: "./video/mmd/mmd_q_16.webm", srcMp4: "./video/mmd/mmd_q_16.mp4", label: "Q角色休闲动作展示" },
    // 水狗
    { srcWebm: "./video/dog/dog_hero_00.webm", srcMp4: "./video/dog/dog_hero_00.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_01.webm", srcMp4: "./video/dog/dog_hero_01.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_02.webm", srcMp4: "./video/dog/dog_hero_02.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_03.webm", srcMp4: "./video/dog/dog_hero_03.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_04.webm", srcMp4: "./video/dog/dog_hero_04.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_05.webm", srcMp4: "./video/dog/dog_hero_05.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_06.webm", srcMp4: "./video/dog/dog_hero_06.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_07.webm", srcMp4: "./video/dog/dog_hero_107.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_08.webm", srcMp4: "./video/dog/dog_hero_08.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_09.webm", srcMp4: "./video/dog/dog_hero_09.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_10.webm", srcMp4: "./video/dog/dog_hero_10.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_11.webm", srcMp4: "./video/dog/dog_hero_11.mp4", label: "神魔诀角色动作展示" },

    { srcWebm: "./video/dog/dog_hero_13.webm", srcMp4: "./video/dog/dog_hero_13.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_14.webm", srcMp4: "./video/dog/dog_hero_14.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_15.webm", srcMp4: "./video/dog/dog_hero_15.mp4", label: "神魔诀角色动作展示" },
    { srcWebm: "./video/dog/dog_hero_16.webm", srcMp4: "./video/dog/dog_hero_16.mp4", label: "神魔诀角色动作展示" },
    // 帧速率
    { srcWebm: "./video/zsl/baby.webm", srcMp4: "./video/zsl/baby.mp4", label: "幼儿生气动画" },
    { srcWebm: "./video/zsl/boy.webm", srcMp4: "./video/zsl/boy.mp4", label: "走和跳动动画" },
    { srcWebm: "./video/zsl/zsl_anima01.webm", srcMp4: "./video/zsl/zsl_anima01.mp4", label: "玉米小人儿激动动画" },
    { srcWebm: "./video/zsl/jxb_jump.webm", srcMp4: "./video/zsl/jxb_jump.mp4", label: "小僵尸跳动动画" },
    { srcWebm: "./video/zsl/zsl_guai00.webm", srcMp4: "./video/zsl/zsl_guai00.mp4", label: "多脸怪动画" },
    { srcWebm: "./video/zsl/zsl_guai01.webm", srcMp4: "./video/zsl/zsl_guai01.mp4", label: "多牙齿怪动画" },
    { srcWebm: "./video/zsl/zsl_guai04.webm", srcMp4: "./video/zsl/zsl_guai04.mp4", label: "蝎子怪攻击动画" },
    { srcWebm: "./video/zsl/zsl_guai05.webm", srcMp4: "./video/zsl/zsl_guai05.mp4", label: "绿叶怪弓箭手" },
    { srcWebm: "./video/zsl/zsl_guai06.webm", srcMp4: "./video/zsl/zsl_guai06.mp4", label: "变异蘑菇怪砍你" },
    { srcWebm: "./video/zsl/zsl_zs.webm", srcMp4: "./video/zsl/zsl_zs.mp4", label: "小泡泡龙武士" },
    { srcWebm: "./video/zsl/zsl_guai07.webm", srcMp4: "./video/zsl/zsl_guai07.mp4", label: "大胡子法师" },
    { srcWebm: "./video/zsl/zsl_guai08.webm", srcMp4: "./video/zsl/zsl_guai08.mp4", label: "AI弓箭手射箭" },
    { srcWebm: "./video/zsl/zsl_hh01.webm", srcMp4: "./video/zsl/zsl_hh01.mp4", label: "小狮子跑动动画" },
    { srcWebm: "./video/zsl/zsl_hh04.webm", srcMp4: "./video/zsl/zsl_hh04.mp4", label: "小狮子转身展示成果" },
    { srcWebm: "./video/zsl/zsl_hh05.webm", srcMp4: "./video/zsl/zsl_hh05.mp4", label: "小狮子落下动画" },
    { srcWebm: "./video/zsl/zsl_hh07.webm", srcMp4: "./video/zsl/zsl_hh07.mp4", label: "小狮子和好友玩搭积木" }
];
// DOM加载完成后初始化
document.addEventListener("DOMContentLoaded", () => {
    initializeVideoPlayer(videoData, "video-list");
});